services:
  dev:
    build:
        context: ../.
        dockerfile: docker/Dockerfile
    image: dev_rs2:rs2_v2
    container_name: dev_rs2
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - MESA_LOADER_DRIVER_OVERRIDE=llvmpipe
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PROJECT_ROOT}/rs2_ws/src:/docker_rs2_ws/src
    working_dir: /docker_rs2_ws

    network_mode: host
    stdin_open: true
    tty: true
    command: bash
